name: tarp # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.10.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Rust Code Coverage Reporter # 79 char long summary
description: |
  Rust Code Coverage Reporter

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  tarp:
    plugin: rust
    source: .
    build-packages:
        - libssl-dev
        - pkg-config
    
apps:
  tarp:
    command: tarp
    plugs: [home]
